numpy can be imported in python as shown below

In [78]:
import numpy as np

One way to initialize an array is using a Python sequence, such as a list. For example:


In [2]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a) 

[1 2 3 4 5 6]


One major difference is that slice indexing of a list copies the elements into a new list, but slicing an array returns a view: an object that refers to the data in the original array. The original array can be mutated using the view.

In [3]:
a = np.array([1,2,3,4,5])
b = a[3:] # b=[4,5]
b[0] = 40  # b = [40,5]
print(a)

[ 1  2  3 40  5]


Two- and higher-dimensional arrays can be initialized from nested Python sequences:

In [4]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print(a[1, 3])
print(a[1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
8
[[ 5  6  7  8]
 [ 9 10 11 12]]


Array attributes
1. ndim
it shows the number of dimensions in the array.

In [6]:
a.ndim

2

2. shape
The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension.

In [7]:
a.shape

(3, 4)

In [8]:
len(a.shape) == a.ndim

True


3.Size
The fixed, total number of elements in array is contained in the size attribute.


In [9]:
a.size

12


4.dtype
Arrays are typically “homogeneous”, meaning that they contain elements of only one “data type”. The data type is recorded in the dtype attribute.

In [17]:
a.dtype

dtype('int64')


Creating a basic array


we can create arrays using the folllowing functions-
 zeros,
 ones,
 empty,
 arange,
 linspace

In [18]:
np.zeros(2)

array([0., 0.])

In [19]:
np.ones(2)

array([1., 1.])

In [20]:
np.empty(2)

array([1., 1.])

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [23]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Sorting the array

You can quickly sort the numbers in ascending order with:

In [25]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In addition to sort, which returns a sorted copy of an array, you can use:

argsort, which is an indirect sort along a specified axis,

lexsort, which is an indirect stable sort on multiple keys,

searchsorted, which will find elements in a sorted array, and

partition, which is a partial sort.

Addition of arrays

In [27]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [42]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x,y),axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
z = y.T
np.concatenate((x,z),axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

Reshaping an array

In [45]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [47]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [60]:
np.reshape(a, shape=(2,3), order="C")

array([[0, 1, 2],
       [3, 4, 5]])

a is the array to be reshaped.

shape is the new shape you want. You can specify an integer or a tuple of integers. If you specify an integer, the result will be an array of that length. The shape should be compatible with the original shape.

order: C means to read/write the elements using C-like index order, F means to read/write the elements using Fortran-like index order, A means to read/write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise. (This is an optional parameter and doesn’t need to be specified.)

Converting 1D array to 2D array

Using np.newaxis will increase the dimensions of your array by one dimension when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

In [63]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

You can explicitly convert a 1D array to either a row vector or a column vector using np.newaxis. For example, you can convert a 1D array to a row vector by inserting an axis along the first dimension:

In [65]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [66]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

You can also expand an array by inserting a new axis at a specified position with np.expand_dims.

In [71]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [79]:
c = np.expand_dims(a,axis=0)
c.shape

(1, 3, 4)

In [84]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b1=a[0,:]
print(b1)

[1 2 3 4]


Array Operations 

1.vstack

In [93]:
a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
               [4, 4]])
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

2.hstack

In [94]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

3.hsplit


In [105]:
x = np.arange(1, 25).reshape(2,12)
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [96]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

4.Sum


In [107]:
a = np.array([1, 2, 3, 4])

a.sum()

np.int64(10)

5.Max,Min

In [111]:
data = np.arange(0,10)
print(data)
print(data.max())
print(data.min())


[0 1 2 3 4 5 6 7 8 9]
9
0


6.Unique

In [113]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


To get the indices of unique values in a NumPy array (an array of first index positions of unique values in the array), just pass the return_index argument in np.unique() as well as your array.

In [114]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


You can pass the return_counts argument in np.unique() along with your array to get the frequency count of unique values in a NumPy array.

In [115]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


7.Transpose

Transpose can be done in 3
 ways

In [119]:
arr = np.arange(6).reshape((2, 3))
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [121]:
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [122]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

8.Flip

In [125]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)
print(reversed_arr)

[8 7 6 5 4 3 2 1]


In [129]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


9.Flatten


you can use flatten to flatten your array into a 1D array.

In [130]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

When you use flatten, changes to your new array won’t change the parent array.

10.Ravel

when you use ravel, the changes you make to the new array will affect the parent array.

In [131]:
a2 = x.ravel()
a2[0] = 98
print(x)  # Original array
print(a2)  # New array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]
